import "./globals.css";
import type { Metadata } from "next";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import Navigation from "@/components/layout/Navigation";
import Footer from "@/components/layout/Footer";
import Wrapper from "@/components/common/Wrapper";

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: {
 children: React.ReactNode;
}) {
 return (
  <html lang="en">
   <body className={inter.className}>
    <Navigation />
    <Wrapper>{children}</Wrapper>
    <Footer />
   </body>
  </html>
 );
}
